# Generated by Django 5.1.2 on 2025-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stationary", "Stationary"),
                            ("electonics", "Electonics"),
                            ("food", "Food"),
                        ],
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
