# Generated by Django 5.1.7 on 2025-03-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
