# Generated by Django 5.1.7 on 2025-03-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profil",
            name="image",
            field=models.ImageField(default="face.jpeg", upload_to="Profile_images"),
        ),
    ]
